export const GAME_CONSTANTS = {
  // World
  WORLD_WIDTH: 5000,
  WORLD_HEIGHT: 5000,
  WORLD_START_X: 2500,
  WORLD_START_Y: 2500,

  // Player
  PLAYER_WIDTH: 40,
  PLAYER_HEIGHT: 40,
  PLAYER_MAX_SPEED: 10,
  PLAYER_ACCELERATION: 0.2,
  PLAYER_FRICTION: 0.95,
  PLAYER_ROTATION_SPEED: 0.05,
  PLAYER_TRAIL_LENGTH: 100,

  // Camera
  CAMERA_FOLLOW_SPEED: 0.1,

  // Canvas
  CANVAS_WIDTH: 1200,
  CANVAS_HEIGHT: 800,
};
