export const GAME_CONSTANTS = {
  // World
  WORLD_WIDTH: 5000,
  WORLD_HEIGHT: 5000,
  WORLD_START_X: 2500,
  WORLD_START_Y: 2500,

  // Player
  PLAYER_WIDTH: 40,
  PLAYER_HEIGHT: 60,
  PLAYER_MAX_SPEED: 10,
  PLAYER_ACCELERATION: 0.1,
  PLAYER_FRICTION: 0.95,
  PLAYER_ROTATION_SPEED: 0.05,
  PLAYER_MAX_HUNGER: 100,
  PLAYER_HUNGER_DRAIN: 0.02,
  PLAYER_TRAIL_LENGTH: 30,
  PLAYER_SPIKE_LENGTH: 40,
  PLAYER_SPIKE_WIDTH: 7,

  // Camera
  CAMERA_ZOOM: 0.67,
  CAMERA_FOLLOW_SPEED: 0.1,

  // Boids
  BOID_COUNT: 450,
  BOID_SIZE: 12,
  BOID_BASE_MAX_SPEED: 3,
  BOID_PERCEPTION_RADIUS: 50,
  BOID_SEPARATION_DISTANCE: 50,
  BOID_TRAIL_LENGTH: 16,
  BOID_VISIBILITY_RADIUS: 800,
  BOID_HUNGER_VALUE: 5,

  // Leviathans
  LEVIATHAN_COUNT: 2,
  LEVIATHAN_WIDTH_MULTIPLIER: 1.4,
  LEVIATHAN_HEIGHT_MULTIPLIER: 1.4,
  LEVIATHAN_MAX_SPEED: 5,
  LEVIATHAN_CHARGE_SPEED: 15,
  LEVIATHAN_CHARGE_WINDUP: 60,
  LEVIATHAN_CHARGE_DURATION: 60,
  LEVIATHAN_CHARGE_COOLDOWN: 0,
  LEVIATHAN_CHARGE_DETECTION_RADIUS: 500,
  LEVIATHAN_PLAYER_SWITCH_RADIUS: 500,
  LEVIATHAN_STUN_DURATION: 120,
  LEVIATHAN_TRAIL_LENGTH: 16,
  LEVIATHAN_UPDATE_RADIUS: 1500,
  LEVIATHAN_MAX_HEALTH: 10,
  LEVIATHAN_DAMAGE_PER_HIT: 1,

  // Swarmers
  SWARMER_COUNT: 0,
  SWARMER_WIDTH_MULTIPLIER: 1.4,
  SWARMER_HEIGHT_MULTIPLIER: 1.4,
  SWARMER_MAX_SPEED: 4,
  SWARMER_TRAIL_LENGTH: 16,
  SWARMER_UPDATE_RADIUS: 1500,

  // Food Orbs
  FOOD_ORB_COUNT: 8,
  FOOD_ORB_SIZE: 10,
  FOOD_ORB_HUNGER_VALUE: 15,
  FOOD_ORB_LIFETIME: 600,
  FOOD_ORB_SPREAD_SPEED: 3,

  // World Generation
  VORONOI_REGIONS: 70,
  VORONOI_ROCK_PROBABILITY: 0.65,
  VORONOI_GRID_SIZE: 70,
  VORONOI_ROCK_SIZE_MULTIPLIER: 1.8,
  CLEAR_RADIUS: 800,
  PLAYER_SAFE_RADIUS: 250,
  TUNNEL_COUNT: 12,
  TUNNEL_WIDTH: 150,
  TUNNEL_STEPS: 50,

  // Rendering
  LINE_OF_SIGHT_RAYS: 180,
  LINE_OF_SIGHT_DISTANCE: 800,
  GRID_SIZE: 100,
  SHADOW_OPACITY: 0.88,

  // Invincibility
  INVINCIBILITY_DURATION: 180, // 3 seconds at 60fps
};
